### PR TITLE
Fixed #183 - https://github.com/chzyer/readline/issues/183

### PR DESCRIPTION
**Pull request by jlourenc**
Also ran `go mod tidy`

### CODE REVIEW

**Comment by jlourenc** [comment]
Hey @skaldesh, would you mind taking a look at this pull request ? Thanks

**Comment by skaldesh** [comment]
Hi!
Can you quickly describe what this fixes? Thanks

**Comment by skaldesh** [comment]
Hi @jlourenc 
I read the original issue and it mentioned something about typing beyond a single line, causing a line break. Then hitting Ctr+C or Ctrl+M leads to drawing issues.  
I am wondering why you want to merge this in this fork (which exists solely for grumble right now). Is there an issue in grumble that would be fixed by this? I am asking since I tried to reproduce this issue with a grumble app, but it works for me

**Comment by jlourenc** [comment]
Hi @skaldesh , thanks for taking a look at the pull request.

> I read the original issue and it mentioned something about typing beyond a single line, causing a line break. Then hitting Ctr+C or Ctrl+M leads to drawing issues.

The below video demonstrates the issue.

issue

The below video is with the code change provided in this PR, which fixes the issue.

fix

These prototypes use `grumble` and code is basically the template provided in the `README.md` in `grumble` repo.

```
package main

import (
    "github.com/desertbit/grumble"
)

func main() {
    app := grumble.New(&grumble.Config{
	    Name:        "app",
	    Description: "short app description",

	    Flags: func(f *grumble.Flags) {
		    f.String("d", "directory", "DEFAULT", "set an alternative directory path")
		    f.Bool("v", "verbose", false, "enable verbose mode")
	    },
    })
    grumble.Main(app)
}
```

> I am wondering why you want to merge this in this fork (which exists solely for grumble right now). Is there an issue in grumble that would be fixed by this?

The main reason is that I want the fix to be propagated in `grumble` which depends on this fork. The other reason is that the upstream repo does not seem to be maintained, therefore patching upstream and then pulling the change downstream seems unrealistic.

**Comment by skaldesh** [comment]
Great explanation and reasoning. Thank you, will merge this and soon update grumble

**Comment by skaldesh** [comment]
[Grumble PR](https://github.com/desertbit/grumble/pull/28)

**Pull request merged**
